### ISSUE TITLE
Figure out how to break up Datafusion query plans into fragments

### ISSUE THREAD

**Issue by achanana** [cmu-db/15721-s24-scheduler1#5]
We need to break up the Substrait physical query plans into fragments that we pass to the execution engine. As a first step, we should learn more about the structure of these Substrait plans so we have a better idea about how to fragment them.

**Comment by SDTheSlayer** [comment]
We have shifted to using the Datafusion execution plan as our input and have written a basic parser and fragmentor.
Ref: #7 

The next step would be breaking up the query plan more methodologically based on the type of node instead of blindly at every node with multiple children.

**Comment by achanana** [comment]
Marking as done.
